sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: cyt
  alioss:
    #    endpoint: oss-cn-hangzhou.aliyuncs.com
    #    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    #    access-key-secret: U6k1brOZ8gaOIXv3nXbulGTUzy6Pd7
    #    bucket-name: sky-take-out
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSWsNK5ZynLvk6YFbug
    access-key-secret: KYLm0a4esnaGDm09GvVJOXmsYyFA97
    bucket-name: sky-itcast-cyt
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wx68f168583234020a
    secret: 72c137724541a30b0dae65d5493969e0
#    appid: wxcd2e39f677fd30ba
#    secret: 84fbfdf5ea288f0c432d829599083637
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php